secrets:
  accessKey: YOURACCESSKEY
  secretKey: YOURSECRETKEY
tenant:
  buckets:
    - name: mlflow
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 1
      size: 10Gi
      storageClassName: standard
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits: ~
ingress:
  api:
    enabled: true
    ingressClassName: istio
    host: minio.minio.127.0.0.1.nip.io
  console:
    enabled: true
    ingressClassName: istio
    host: console.minio.minio.127.0.0.1.nip.io
