operator:
  replicaCount: 1
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits: ~
console:
  replicaCount: 1
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits: ~
