# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

#TODO: After github.com/gojek/merlin is published, move to Read the Docs Community edition
# Required
version: 1

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: python/sdk/docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: python/sdk/docs/requirements_docs.txt