ClusterConfig:
  EnvironmentConfigPath: ./environment.yaml

DbConfig:
  Host: localhost
  Port: 5432
  User: merlin
  Password: merlin
  Database: merlin

ReactAppConfig:
  HomePage: /merlin
  MerlinURL: http://localhost:8080/v1
  MlpURL: http://localhost:8080/v1

NewRelic:
  Enabled: false

ImageBuilderConfig:
  ArtifactServiceType: nop
  ClusterName: id-dev
  DefaultResources:
    Requests:
      CPU: "1"
      Memory: 512Mi
    Limits:
      CPU: "1"
      Memory: 1Gi
  BaseImage:
    ImageName: ghcr.io/caraml-dev/merlin-pyfunc-base:v0.37.0
    DockerfilePath: docker/Dockerfile
    BuildContextURI: git://github.com/gojek/merlin.git#refs/tags/v0.37.0
    BuildContextSubPath: python
  PredictionJobBaseImage:
    ImageName: ghcr.io/caraml-dev/merlin-pyspark-base:v0.37.0
    DockerfilePath: docker/app.Dockerfile
    BuildContextURI: git://github.com/gojek/merlin.git#refs/tags/v0.37.0
    BuildContextSubPath: python
    MainAppPath: /home/spark/merlin-spark-app/main.py
  BuildNamespace: mlp
  DockerRegistry: ghcr.io/caraml-dev
  BuildTimeout: 10m
  K8sConfig:
    name: id-dev
    cluster:
      server: id-dev.k8s-cluster
      insecure-skip-tls-verify: true
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: gke-gcloud-auth-plugin
        interactiveMode: IfAvailable
        provideClusterInfo: true
  KanikoAdditionalArgs:
    - "--cache=true"
    - "--compressed-caching=false"
    - "--snapshot-mode=redo"
    - "--use-new-run"

BatchConfig:
  Tolerations:
    - Effect: NoSchedule
      Key: batch-job
      Operator: Equal
      Value: "true"
  NodeSelectors:
    node-workload-type: "batch"

AuthorizationConfig:
  AuthorizationEnabled: false

FeatureToggleConfig:
  MonitoringConfig:
    MonitoringEnabled: false
  AlertConfig:
    AlertEnabled: false

MlpAPIConfig:
  APIHost: https://caraml.dev/mlp

StandardTransformerConfig:
  ImageName: ghcr.io/caraml-dev/merlin-transformer:0.25.0
  FeastCoreURL: https://caraml.dev/feast
  FeastCoreAuthAudience: false
  SimulationFeast:
    FeastRedisURL: https://caraml.dev/feast/redis
    FeastBigtableURL: https://caraml.dev/feast/bigtable
  Kafka:
    Brokers: localhost:9092
  Jaeger:
    CollectorURL: localhost:14268/api/traces

MlflowConfig:
  TrackingURL: https://caraml.dev/mlflow
  ArtifactServiceType: nop

PyFuncPublisherConfig:
  Kafka:
    Brokers: localhost:9092
    LingerMS: 1000
    Acks: 0
