projectName: merlin-sdk
packageName: client
generateSourceCodeOnly: true
useOneOfDiscriminatorLookup: true
# Global Properties
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false