/*
 * Merlin
 *
 * API Guide for accessing Merlin's model management, deployment, and serving functionalities
 *
 * API version: 0.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

type Version struct {
	Id          int32             `json:"id,omitempty"`
	ModelId     int32             `json:"model_id,omitempty"`
	MlflowRunId string            `json:"mlflow_run_id,omitempty"`
	MlflowUrl   string            `json:"mlflow_url,omitempty"`
	ArtifactUri string            `json:"artifact_uri,omitempty"`
	Endpoints   []VersionEndpoint `json:"endpoints,omitempty"`
	Properties  *interface{}      `json:"properties,omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	CreatedAt   time.Time         `json:"created_at,omitempty"`
	UpdatedAt   time.Time         `json:"updated_at,omitempty"`
}
