/*
 * Merlin
 *
 * API Guide for accessing Merlin's model management, deployment, and serving functionalities
 *
 * API version: 0.14.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type FileFormat string

// List of FileFormat
const (
	INVALID_FILE_FORMAT FileFormat = "INVALID_FILE_FORMAT"
	CSV                 FileFormat = "CSV"
	PARQUET             FileFormat = "PARQUET"
	AVRO                FileFormat = "AVRO"
	JSON                FileFormat = "JSON"
)
