/*
 * Merlin
 *
 * API Guide for accessing Merlin's model management, deployment, and serving functionalities
 *
 * API version: 0.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type AlertConditionMetricType string

// List of AlertConditionMetricType
const (
	THROUGHPUT_AlertConditionMetricType AlertConditionMetricType = "throughput"
	LATENCY_AlertConditionMetricType    AlertConditionMetricType = "latency"
	ERROR_RATE_AlertConditionMetricType AlertConditionMetricType = "error_rate"
	CPU_AlertConditionMetricType        AlertConditionMetricType = "cpu"
	MEMORY_AlertConditionMetricType     AlertConditionMetricType = "memory"
)
