/*
 * Merlin
 *
 * API Guide for accessing Merlin's model management, deployment, and serving functionalities
 *
 * API version: 0.14.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type SaveMode string

// List of SaveMode
const (
	ERRORIFEXISTS SaveMode = "ERRORIFEXISTS"
	OVERWRITE     SaveMode = "OVERWRITE"
	APPEND        SaveMode = "APPEND"
	IGNORE        SaveMode = "IGNORE"
	ERROR_        SaveMode = "ERROR"
)
