/*
 * Merlin
 *
 * API Guide for accessing Merlin's model deployment functionalities
 *
 * API version: 0.6.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type ResourceRequest struct {
	MinReplica    int32  `json:"min_replica,omitempty"`
	MaxReplica    int32  `json:"max_replica,omitempty"`
	CpuRequest    string `json:"cpu_request,omitempty"`
	MemoryRequest string `json:"memory_request,omitempty"`
}
