/*
 * Merlin
 *
 * API Guide for accessing Merlin's model management, deployment, and serving functionalities
 *
 * API version: 0.14.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type MetricsType string

// List of MetricsType
const (
	CONCURRENCY        MetricsType = "concurrency"
	CPU_UTILIZATION    MetricsType = "cpu_utilization"
	MEMORY_UTILIZATION MetricsType = "memory_utilization"
	RPS                MetricsType = "rps"
)
