/*
 * Merlin
 *
 * API Guide for accessing Merlin's model management, deployment, and serving functionalities
 *
 * API version: 0.14.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type Logger struct {
	Model       *LoggerConfig           `json:"model,omitempty"`
	Transformer *LoggerConfig           `json:"transformer,omitempty"`
	Prediction  *PredictionLoggerConfig `json:"prediction,omitempty"`
}
