/*
 * Merlin
 *
 * API Guide for accessing Merlin's model deployment functionalities
 *
 * API version: 0.6.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type ModelEndpointRuleDestination struct {
	VersionEndpointId string           `json:"version_endpoint_id,omitempty"`
	VersionEndpoint   *VersionEndpoint `json:"version_endpoint,omitempty"`
	Weight            int32            `json:"weight,omitempty"`
}
