/*
Merlin

API Guide for accessing Merlin's model management, deployment, and serving functionalities

API version: 0.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the Toleration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Toleration{}

// Toleration Kubernetes toleration for scheduling pods onto tainted nodes
type Toleration struct {
	// The taint key the toleration applies to
	Key *string `json:"key,omitempty"`
	// 'Exists' or 'Equal' (default: Equal)
	Operator *string `json:"operator,omitempty"`
	// The taint value the toleration matches (only used when operator is Equal)
	Value *string `json:"value,omitempty"`
	// 'NoSchedule', 'PreferNoSchedule', or 'NoExecute'. Empty matches all effects
	Effect *string `json:"effect,omitempty"`
	// Period (seconds) the pod tolerates the taint (only for NoExecute effect)
	TolerationSeconds *int64 `json:"toleration_seconds,omitempty"`
}

// NewToleration instantiates a new Toleration object
func NewToleration() *Toleration {
	this := Toleration{}
	return &this
}

// NewTolerationWithDefaults instantiates a new Toleration object with defaults
func NewTolerationWithDefaults() *Toleration {
	this := Toleration{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *Toleration) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Toleration) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *Toleration) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}
	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *Toleration) SetKey(v string) {
	o.Key = &v
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *Toleration) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Toleration) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *Toleration) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}
	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *Toleration) SetOperator(v string) {
	o.Operator = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *Toleration) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Toleration) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *Toleration) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}
	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *Toleration) SetValue(v string) {
	o.Value = &v
}

// GetEffect returns the Effect field value if set, zero value otherwise.
func (o *Toleration) GetEffect() string {
	if o == nil || IsNil(o.Effect) {
		var ret string
		return ret
	}
	return *o.Effect
}

// GetEffectOk returns a tuple with the Effect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Toleration) GetEffectOk() (*string, bool) {
	if o == nil || IsNil(o.Effect) {
		return nil, false
	}
	return o.Effect, true
}

// HasEffect returns a boolean if a field has been set.
func (o *Toleration) HasEffect() bool {
	if o != nil && !IsNil(o.Effect) {
		return true
	}
	return false
}

// SetEffect gets a reference to the given string and assigns it to the Effect field.
func (o *Toleration) SetEffect(v string) {
	o.Effect = &v
}

// GetTolerationSeconds returns the TolerationSeconds field value if set, zero value otherwise.
func (o *Toleration) GetTolerationSeconds() int64 {
	if o == nil || IsNil(o.TolerationSeconds) {
		var ret int64
		return ret
	}
	return *o.TolerationSeconds
}

// GetTolerationSecondsOk returns a tuple with the TolerationSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Toleration) GetTolerationSecondsOk() (*int64, bool) {
	if o == nil || IsNil(o.TolerationSeconds) {
		return nil, false
	}
	return o.TolerationSeconds, true
}

// HasTolerationSeconds returns a boolean if a field has been set.
func (o *Toleration) HasTolerationSeconds() bool {
	if o != nil && !IsNil(o.TolerationSeconds) {
		return true
	}
	return false
}

// SetTolerationSeconds gets a reference to the given int64 and assigns it to the TolerationSeconds field.
func (o *Toleration) SetTolerationSeconds(v int64) {
	o.TolerationSeconds = &v
}

func (o Toleration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Toleration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Effect) {
		toSerialize["effect"] = o.Effect
	}
	if !IsNil(o.TolerationSeconds) {
		toSerialize["toleration_seconds"] = o.TolerationSeconds
	}
	return toSerialize, nil
}

type NullableToleration struct {
	value *Toleration
	isSet bool
}

func (v NullableToleration) Get() *Toleration {
	return v.value
}

func (v *NullableToleration) Set(val *Toleration) {
	v.value = val
	v.isSet = true
}

func (v NullableToleration) IsSet() bool {
	return v.isSet
}

func (v *NullableToleration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToleration(val *Toleration) *NullableToleration {
	return &NullableToleration{value: val, isSet: true}
}

func (v NullableToleration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToleration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
