/*
 * Merlin
 *
 * API Guide for accessing Merlin's model management, deployment, and serving functionalities
 *
 * API version: 0.14.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type AlertConditionMetricType string

// List of AlertConditionMetricType
const (
	THROUGHPUT AlertConditionMetricType = "throughput"
	LATENCY    AlertConditionMetricType = "latency"
	ERROR_RATE AlertConditionMetricType = "error_rate"
	CPU        AlertConditionMetricType = "cpu"
	MEMORY     AlertConditionMetricType = "memory"
)
