/*
 * Merlin
 *
 * API Guide for accessing Merlin's model management, deployment, and serving functionalities
 *
 * API version: 0.14.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type Gpu struct {
	Values            int32             `json:"values,omitempty"`
	DisplayName       string            `json:"display_name,omitempty"`
	ResourceType      string            `json:"resource_type,omitempty"`
	NodeSelector      map[string]string `json:"node_selector,omitempty"`
	MonthlyCostPerGpu float64           `json:"monthly_cost_per_gpu,omitempty"`
}
