# coding: utf-8

"""
    Merlin

    API Guide for accessing Merlin's model management, deployment, and serving functionalities  # noqa: E501

    OpenAPI spec version: 0.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OperationTracing(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'preprocess': 'PipelineTracing',
        'postprocess': 'PipelineTracing'
    }

    attribute_map = {
        'preprocess': 'preprocess',
        'postprocess': 'postprocess'
    }

    def __init__(self, preprocess=None, postprocess=None):  # noqa: E501
        """OperationTracing - a model defined in Swagger"""  # noqa: E501
        self._preprocess = None
        self._postprocess = None
        self.discriminator = None
        if preprocess is not None:
            self.preprocess = preprocess
        if postprocess is not None:
            self.postprocess = postprocess

    @property
    def preprocess(self):
        """Gets the preprocess of this OperationTracing.  # noqa: E501


        :return: The preprocess of this OperationTracing.  # noqa: E501
        :rtype: PipelineTracing
        """
        return self._preprocess

    @preprocess.setter
    def preprocess(self, preprocess):
        """Sets the preprocess of this OperationTracing.


        :param preprocess: The preprocess of this OperationTracing.  # noqa: E501
        :type: PipelineTracing
        """

        self._preprocess = preprocess

    @property
    def postprocess(self):
        """Gets the postprocess of this OperationTracing.  # noqa: E501


        :return: The postprocess of this OperationTracing.  # noqa: E501
        :rtype: PipelineTracing
        """
        return self._postprocess

    @postprocess.setter
    def postprocess(self, postprocess):
        """Sets the postprocess of this OperationTracing.


        :param postprocess: The postprocess of this OperationTracing.  # noqa: E501
        :type: PipelineTracing
        """

        self._postprocess = postprocess

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OperationTracing, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OperationTracing):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
