# coding: utf-8

"""
    Merlin

    API Guide for accessing Merlin's model management, deployment, and serving functionalities

    The version of the OpenAPI document: 0.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ProbeConfig(BaseModel):
    """
    ProbeConfig
    """ # noqa: E501
    path: Optional[StrictStr] = Field(default=None, description="Path for HTTP probe")
    port: Optional[StrictInt] = Field(default=None, description="Port for the probe")
    scheme: Optional[StrictStr] = Field(default=None, description="Scheme for HTTP probe (HTTP or HTTPS)")
    initial_delay_seconds: Optional[StrictInt] = Field(default=None, description="Initial delay before starting the probe (seconds)")
    timeout_seconds: Optional[StrictInt] = Field(default=None, description="Timeout for the probe (seconds)")
    period_seconds: Optional[StrictInt] = Field(default=None, description="Period between probe checks (seconds)")
    success_threshold: Optional[StrictInt] = Field(default=None, description="Number of successes required to be considered healthy")
    failure_threshold: Optional[StrictInt] = Field(default=None, description="Number of failures before considered unhealthy")
    __properties: ClassVar[List[str]] = ["path", "port", "scheme", "initial_delay_seconds", "timeout_seconds", "period_seconds", "success_threshold", "failure_threshold"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProbeConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ProbeConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "path": obj.get("path"),
            "port": obj.get("port"),
            "scheme": obj.get("scheme"),
            "initial_delay_seconds": obj.get("initial_delay_seconds"),
            "timeout_seconds": obj.get("timeout_seconds"),
            "period_seconds": obj.get("period_seconds"),
            "success_threshold": obj.get("success_threshold"),
            "failure_threshold": obj.get("failure_threshold")
        })
        return _obj


