autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi

service:
  # Type of service. Set to "None" to disable the service entirely
  type: NodePort
  ports:
  - name: http2
    nodePort: 8083
    port: 80
    protocol: TCP
    targetPort: 80
