dependencies:
  - name: postgresql
    repository: https://charts.helm.sh/stable
    version: 7.0.0
    alias: merlin-postgresql
    condition: merlin-postgresql.enabled
  - name: postgresql
    repository: https://charts.helm.sh/stable
    version: 7.0.0
    alias: mlflow-postgresql
    condition: mlflow-postgresql.enabled
