model_id: "test-model"
model_version: "0.1.0"
inference_schema:
  # Inference schema associated with the model id and version. For full documentation on the support configuration,
  # refer to the Merlin SDK. Example below is for a binary classification model.

  model_prediction_output:
    output_class: "BinaryClassificationOutput"
    prediction_score_column: "score"
    actual_label_column: "actual_label"
    positive_class_label: "positive"
    negative_class_label: "negative"
    score_threshold: 0.5

  feature_types:
    distance: "int64"
    transaction: "float64"
  prediction_id_column: "prediction_id"
observability_backend:
  # Supported backend types:
  #  - ARIZE
  type: "ARIZE"
  # Required if observability_backend.type is ARIZE
  arize_config:
    api_key: "SECRET_API_KEY"
    space_key: "SECRET_SPACE_KEY"
observation_source:
  # Supported consumer types:
  #  - KAFKA
  type: "KAFKA"
  # Required if consumer.type is KAFKA
  kafka_config:
    topic: "test-topic"
    bootstrap_servers: "localhost:9092"
    group_id: "test-group"
    # (Optional) The maximum number of records returned in a single call to poll(). Default: 100
    batch_size: 100
    # (Optional) Additional consumer configuration to be passed to KafkaConsumer.
    additional_consumer_config:
      "auto.offset.reset": "latest"
