[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
markers = [
    "integration: mark a test as integration test"
]

[tool.mypy]
exclude = "test.*"

[[tool.mypy.overrides]]
module = ["arize.*", "merlin.*", "confluent_kafka.*", "caraml.upi.*", "pyarrow.*"]
ignore_missing_imports = true
