{{- if eq .Values.merlin.database.type "cloudsql" -}}
{{- if eq .Values.cloudsql.enabled true -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudsql.password.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "merlin.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ include "merlin.chart" . }}
    app.kubernetes.io/name: {{ include "merlin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    gojek.com/app: merlin
    gojek.com/team: dsp
    gojek.com/stream: dsp
    gojek.com/orchestrator: gitlab
    gojek.com/environment: {{ .Values.merlin.environment }}
type: Opaque
stringData:
{{- printf "%s: %s" .Values.cloudsql.password.secretKey .Values.cloudsql.password.value | indent 2 -}}
{{- end -}}
{{- end -}}
