{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.merlin.database.password.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "merlin.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ include "merlin.chart" . }}
    app.kubernetes.io/name: {{ include "merlin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    gojek.com/app: merlin
    gojek.com/team: dsp
    gojek.com/stream: dsp
    gojek.com/orchestrator: gitlab
    gojek.com/environment: {{ .Values.merlin.environment }}
type: Opaque
stringData:
  database-password: {{ .Values.merlin.database.password.value }}
{{- end }}
