{{- if not (index .Values "merlin-postgresql" "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-merlin-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "merlin.name" . }}
    release: {{ .Release.Name }}
    helm.sh/chart: {{ include "merlin.chart" . }}
    app.kubernetes.io/name: {{ include "merlin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  postgresql-password: {{ index .Values "merlin-postgresql" "postgresqlPassword" }}
{{- end }}
