{{- if .Values.merlin.alert.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gitlab-token
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "merlin.name" . }}
    release: {{ .Release.Name }}
    helm.sh/chart: {{ include "merlin.chart" . }}
    app.kubernetes.io/name: {{ include "merlin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  gitlab-token: {{ .Values.merlin.gitlab.token }}
{{- end }}
