apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "merlin.fullname" .}}-environments
  labels:
    app: {{ include "merlin.name" . }}
    release: {{ .Release.Name }}
    helm.sh/chart: {{ include "merlin.chart" . }}
    app.kubernetes.io/name: {{ include "merlin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  environment.yaml: |-
{{- if .Values.merlin.environmentConfigs }}
{{ toYaml .Values.merlin.environmentConfigs | indent 4 }}
{{- end }}
  imageBuilderK8sConfig: |-
{{- if .Values.merlin.imageBuilder.k8sConfig }}
{{ .Values.merlin.imageBuilder.k8sConfig | b64dec | indent 4 }}
{{- end }}
    
