apiVersion: v1
kind: Service
metadata:
  name: {{ template "merlin.fullname" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "merlin.name" . }}
    release: {{ .Release.Name }}
    helm.sh/chart: {{ include "merlin.chart" . }}
    app.kubernetes.io/name: {{ include "merlin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.merlin.service.externalPort }}
      targetPort: {{ .Values.merlin.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "merlin.name" .}}
    release: {{ .Release.Name }}
