{{- if .Values.swagger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "merlin.fullname" .}}-swagger
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "merlin.name" . }}-swagger
    release: {{ .Release.Name }}
    helm.sh/chart: {{ include "merlin.chart" . }}
    app.kubernetes.io/name: {{ include "merlin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.swagger.service.externalPort }}
      targetPort: {{ .Values.swagger.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "merlin.name" . }}
    release: {{ .Release.Name }}
{{- end }}
