transformerConfig:
  feast:
    - project: default
      entities:
        - name: merchant_id
          valueType: STRING
          jsonPath: $.merchants[*].id
      features:
        - name: merchant_discovery:delivery_estimate
          valueType: DOUBLE
          defaultValue: '0'