// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mlflow "github.com/gojek/merlin/mlflow"
	mock "github.com/stretchr/testify/mock"
)

// ClientFactory is an autogenerated mock type for the ClientFactory type
type ClientFactory struct {
	mock.Mock
}

// NewClient provides a mock function with given fields: httpClient, trackingURL
func (_m *ClientFactory) NewClient(httpClient *http.Client, trackingURL string) mlflow.Client {
	ret := _m.Called(httpClient, trackingURL)

	var r0 mlflow.Client
	if rf, ok := ret.Get(0).(func(*http.Client, string) mlflow.Client); ok {
		r0 = rf(httpClient, trackingURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mlflow.Client)
		}
	}

	return r0
}
