apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: message-dumper
  namespace: mlp
  annotations:
    autoscaling.knative.dev/min-scale: "1"
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
