name: External Dependencies CI Workflow
on:
  push:
    branches: 
    - main 
  pull_request:
  
jobs:
  publish-mlflow-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push MLflow Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io
          repository: gojek/mlflow
          path: mlflow
          dockerfile: mlflow/Dockerfile
          build_args: MLFLOW_VERSION=1.3.0
          tags: 1.3.0
