name: External Dependencies CI Workflow
on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  publish-mlflow-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push MLflow Docker image
        uses: docker/build-push-action@v5
        with:
          context: mlflow
          file: mlflow/Dockerfile
          build-args: MLFLOW_VERSION=1.3.0
          tags: ghcr.io/caraml-dev/mlflow:1.3.0
