# This workflow triggers update in caraml doc

name: Trigger Caraml doc update

on:
  push:
    branches: 
    - main 
    tags:
    - v*
  pull_request:

jobs:
  trigger-sync:
    name: Pull Docs CI
    uses: caraml-dev/docs/.github/actions/trigger-pull-docs.yml@sync-action
    with:
      module: 'model'
      git_https: 'https://github.com/gojek/merlin.git'
      doc_folder: 'docs'
      branch: 'main'