# This workflow triggers update in caraml doc

name: Trigger Caraml doc update

on:
  push:
    branches: 
    - main 
    tags:
    - v*
  pull_request:

jobs:
  trigger-sync:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/github-script@v6
    #   with:
    #     github-token: ${{ secrets.CARAML_SYNC }}
    #     script: |
    #       await github.rest.actions.createWorkflowDispatch({
    #         owner: 'caraml-dev',
    #         repo: 'docs',
    #         workflow_id: 'test_pull_docs.yml',
    #         ref: 'main'
    #       })
      - uses: actions/checkout@v3
      - name: checkout caraml actions
        uses: actions/checkout@v3
        with:
          repository: caraml-dev/docs
          path: .github/actions
          ref: 'sync'
          token: ${{ secrets.CARAML_SYNC }}
      - id: trigger-caraml
        uses: ./.github/actions/trigger-doc-pull/action.yml
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.trigger-caraml.outputs.random-number }}
        shell: bash