# This workflow triggers sync of docs to caraml-dev/docs

name: Trigger CaraML Docs Sync

on:
  push:
    branches: 
    - main 
    tags:
    - v*
  pull_request:

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Remote Doc Sync Workflow
        uses: caraml-dev/docs/.github/actions/trigger-remote-docs-sync@main
        with:
          module: 'model'
          git_https: 'https://github.com/gojek/merlin.git'
          doc_folder: 'docs'
          branch: ${{ github.sha }}
          credentials: ${{ secrets.CARAML_SYNC }}